### ISSUE TITLE
Jenkins evaluates some used files as unused.

### ISSUE THREAD

**Issue by anetacamo** [Praqma/jekyll#15]
<img width="1034" alt="screen shot 2018-02-01 at 17 48 18" src="https://user-images.githubusercontent.com/30343653/35691253-40f4ab6a-0778-11e8-8a2b-a33557785338.png">

The job keeps failing due to unused files. Some of those files are referenced through CSS (for example on-symbol.png) and some of the pictures are generated from the liquid code snippets (first one in the first picture). They are being used but Jenkins evaluates them as unused and reports a failure. 

![screen shot 2018-02-01 at 17 22 41](https://user-images.githubusercontent.com/30343653/35690224-a504dc36-0775-11e8-88b2-3d50f58ad6d7.png)
![screen shot 2018-02-01 at 17 33 53](https://user-images.githubusercontent.com/30343653/35691244-3b59f912-0778-11e8-9f9f-d0448a421b88.png)

**Comment by mortench3000** [comment]
This issue is related to the `analyzer.rb` script running in `https://jenkins.praqma.cloud/view/Website_Jobs/job/Web_www.code-conf.com-resource-analysis/`
Also referenced in this slack thread: https://praqma.slack.com/archives/C6M0RMK9U/p1516482048000036

Issue is that in the scan for unused images, only `.md` and `.html` files are scanned - However it is clear that `.css` files need to be scanned as well.

Including `.css` files in the scan currently leaves this list of 7 unused images:
```
images/includes/newsletter-close-btn.png
images/audience_auditorium.jpg
images/codeconf_jc_nw3.png
images/pages/speakers/speakers_filter.png
images/pages/academy2018/graduates.jpg
images/pages/index/get-involved-4.jpg
images/pages/code-alliance/alliance-seven2.jpg
```

**Comment by sheeeng** [comment]
Related to #18. Check a better way to tag so as to increment the image version that will be automatically build by Docker Hub.
